name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main  # or master, adjust to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAAZ }}
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT}" > ${GITHUB_WORKSPACE}/sa.json
          firebase deploy --only hosting --project saaz-16ae6 --token "$(firebase login:ci || true)" --non-interactive
